spring.application.name=ProductService
# Logging Configuration
logging.level.root=INFO
logging.level.org.example.productservice=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=INFO
# Log output
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/productservicesep26
spring.datasource.username=productservicesep26
#spring.datasource.password=Gyan@0112
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
