spring.application.name=ProductService

# Logging Configuration
logging.level.root=INFO
logging.level.org.example.productservice=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot=INFO

# Log output
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
